const data = {
  products: [
    {
      _id: "1",
      name: "Nike slim shirt",
      category: "Shirts",
      image: "/image/p1.jpg",
      price: 120,
      brand: "Nikee",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "addidas slim shirt",
      category: "Shirts",
      image: "/image/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Nike slim shirt",
      category: "Shirts",
      image: "/image/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike slim shirt",
      category: "Shirts",
      image: "/image/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Nike slim shirt",
      category: "Shirts",
      image: "/image/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Nike slim shirt",
      category: "Shirts",
      image: "/image/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "7",
      name: "Nike slim shirt",
      category: "Shirts",
      image: "/image/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
